[package]
name = "opus-kman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["web-tests"]

[dependencies]
audiopus_sys = "0.2"
cpal = "0.15"
bytes-kman = "0.3"
log = "0.4"


